FROM node:20-bullseye-slim

# Install system dependencies required for compiling native C++ addons
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN mkdir /workspace

CMD ["node", "server.js"]